import { ParamDef } from './types';

// Transform group parameters
export const transformParams: ParamDef[] = [
  {
    id: 'transform.posX',
    group: 'transform',
    label: '位置 X',
    appliesTo: ['video', 'image', 'text', 'sticker', 'adjustmentLayer', 'shape'],
    keyframe: true,
    kind: 'number',
    min: -5000,
    max: 5000,
    step: 1,
    unit: 'px',
    clamp: 'soft',
    defaultValue: 0,
    ui: { control: 'slider+input' },
  },
  {
    id: 'transform.posY',
    group: 'transform',
    label: '位置 Y',
    appliesTo: ['video', 'image', 'text', 'sticker', 'adjustmentLayer', 'shape'],
    keyframe: true,
    kind: 'number',
    min: -5000,
    max: 5000,
    step: 1,
    unit: 'px',
    clamp: 'soft',
    defaultValue: 0,
    ui: { control: 'slider+input' },
  },
  {
    id: 'transform.scale',
    group: 'transform',
    label: '缩放',
    appliesTo: ['video', 'image', 'text', 'sticker', 'adjustmentLayer', 'shape'],
    keyframe: true,
    kind: 'number',
    min: 0,
    max: 1000,
    step: 1,
    unit: '%',
    clamp: 'soft',
    defaultValue: 100,
    ui: { control: 'slider+input' },
  },
  {
    id: 'transform.rotate',
    group: 'transform',
    label: '旋转',
    appliesTo: ['video', 'image', 'text', 'sticker', 'adjustmentLayer', 'shape'],
    keyframe: true,
    kind: 'number',
    min: 0,
    max: 360,
    step: 0.1,
    unit: '°',
    clamp: 'soft',
    defaultValue: 0,
    ui: { control: 'slider+input', precision: 1 },
  },
  {
    id: 'transform.opacity',
    group: 'transform',
    label: '不透明度',
    appliesTo: ['video', 'image', 'text', 'sticker', 'adjustmentLayer', 'shape'],
    keyframe: true,
    kind: 'number',
    min: 0,
    max: 100,
    step: 1,
    unit: '%',
    clamp: 'hard',
    defaultValue: 100,
    ui: { control: 'slider+input' },
  },
  {
    id: 'transform.blendMode',
    group: 'transform',
    label: '混合模式',
    appliesTo: ['video', 'image', 'text', 'sticker', 'adjustmentLayer', 'shape'],
    keyframe: false,
    kind: 'enum',
    defaultValue: 'normal',
    options: [
      { label: '正常', value: 'normal' },
      { label: '变暗', value: 'darken' },
      { label: '正片叠底', value: 'multiply' },
      { label: '滤色', value: 'screen' },
      { label: '叠加', value: 'overlay' },
    ],
    ui: { control: 'select' },
  },
];

// Color Basic parameters
export const colorBasicParams: ParamDef[] = [
  {
    id: 'color.brightness',
    group: 'colorBasic',
    label: '亮度',
    appliesTo: ['video', 'image', 'adjustmentLayer'],
    keyframe: true,
    kind: 'number',
    min: -50,
    max: 50,
    step: 1,
    clamp: 'hard',
    defaultValue: 0,
    ui: { control: 'slider+input' },
  },
  {
    id: 'color.contrast',
    group: 'colorBasic',
    label: '对比度',
    appliesTo: ['video', 'image', 'adjustmentLayer'],
    keyframe: true,
    kind: 'number',
    min: -50,
    max: 50,
    step: 1,
    clamp: 'hard',
    defaultValue: 0,
    ui: { control: 'slider+input' },
  },
  {
    id: 'color.saturation',
    group: 'colorBasic',
    label: '饱和度',
    appliesTo: ['video', 'image', 'adjustmentLayer'],
    keyframe: true,
    kind: 'number',
    min: -50,
    max: 50,
    step: 1,
    clamp: 'hard',
    defaultValue: 0,
    ui: { control: 'slider+input' },
  },
];

// LUT metadata and adjustment parameters. Rendering currently falls back to
// color.* values, while these keep LUT panel state valid and serializable.
export const lutParams: ParamDef[] = [
  {
    id: 'lut.id',
    group: 'lut',
    label: 'LUT ID',
    appliesTo: ['video', 'image', 'adjustmentLayer'],
    keyframe: false,
    kind: 'enum',
    defaultValue: '',
    options: [{ label: '未应用', value: '' }],
    ui: { control: 'select' },
  },
  {
    id: 'lut.name',
    group: 'lut',
    label: 'LUT 名称',
    appliesTo: ['video', 'image', 'adjustmentLayer'],
    keyframe: false,
    kind: 'enum',
    defaultValue: '',
    options: [{ label: '未应用', value: '' }],
    ui: { control: 'select' },
  },
  {
    id: 'lut.data',
    group: 'lut',
    label: 'LUT 数据',
    appliesTo: ['video', 'image', 'adjustmentLayer'],
    keyframe: false,
    kind: 'enum',
    defaultValue: '',
    options: [{ label: '无', value: '' }],
    ui: { control: 'select' },
  },
  {
    id: 'lut.intensity',
    group: 'lut',
    label: 'LUT 强度',
    appliesTo: ['video', 'image', 'adjustmentLayer'],
    keyframe: true,
    kind: 'number',
    min: 0,
    max: 100,
    step: 1,
    unit: '%',
    clamp: 'hard',
    defaultValue: 100,
    ui: { control: 'slider+input' },
  },
  {
    id: 'lut.temperature',
    group: 'lut',
    label: '色温',
    appliesTo: ['video', 'image', 'adjustmentLayer'],
    keyframe: true,
    kind: 'number',
    min: -100,
    max: 100,
    step: 1,
    clamp: 'hard',
    defaultValue: 0,
    ui: { control: 'slider+input' },
  },
  {
    id: 'lut.tint',
    group: 'lut',
    label: '色调',
    appliesTo: ['video', 'image', 'adjustmentLayer'],
    keyframe: true,
    kind: 'number',
    min: -100,
    max: 100,
    step: 1,
    clamp: 'hard',
    defaultValue: 0,
    ui: { control: 'slider+input' },
  },
  {
    id: 'lut.shadows',
    group: 'lut',
    label: '暗部',
    appliesTo: ['video', 'image', 'adjustmentLayer'],
    keyframe: true,
    kind: 'number',
    min: -100,
    max: 100,
    step: 1,
    clamp: 'hard',
    defaultValue: 0,
    ui: { control: 'slider+input' },
  },
  {
    id: 'lut.highlights',
    group: 'lut',
    label: '高光',
    appliesTo: ['video', 'image', 'adjustmentLayer'],
    keyframe: true,
    kind: 'number',
    min: -100,
    max: 100,
    step: 1,
    clamp: 'hard',
    defaultValue: 0,
    ui: { control: 'slider+input' },
  },
  {
    id: 'lut.exposure',
    group: 'lut',
    label: '曝光',
    appliesTo: ['video', 'image', 'adjustmentLayer'],
    keyframe: true,
    kind: 'number',
    min: -100,
    max: 100,
    step: 1,
    clamp: 'hard',
    defaultValue: 0,
    ui: { control: 'slider+input' },
  },
  {
    id: 'lut.contrast',
    group: 'lut',
    label: 'LUT 对比',
    appliesTo: ['video', 'image', 'adjustmentLayer'],
    keyframe: true,
    kind: 'number',
    min: 0,
    max: 200,
    step: 1,
    clamp: 'hard',
    defaultValue: 100,
    ui: { control: 'slider+input' },
  },
  {
    id: 'lut.saturation',
    group: 'lut',
    label: 'LUT 饱和',
    appliesTo: ['video', 'image', 'adjustmentLayer'],
    keyframe: true,
    kind: 'number',
    min: 0,
    max: 200,
    step: 1,
    clamp: 'hard',
    defaultValue: 100,
    ui: { control: 'slider+input' },
  },
  {
    id: 'lut.vibrance',
    group: 'lut',
    label: '自然饱和',
    appliesTo: ['video', 'image', 'adjustmentLayer'],
    keyframe: true,
    kind: 'number',
    min: -100,
    max: 100,
    step: 1,
    clamp: 'hard',
    defaultValue: 0,
    ui: { control: 'slider+input' },
  },
  {
    id: 'lut.lutStrength',
    group: 'lut',
    label: '预设强度',
    appliesTo: ['video', 'image', 'adjustmentLayer'],
    keyframe: true,
    kind: 'number',
    min: 0,
    max: 100,
    step: 1,
    unit: '%',
    clamp: 'hard',
    defaultValue: 100,
    ui: { control: 'slider+input' },
  },
  {
    id: 'lut.vignette',
    group: 'lut',
    label: '暗角',
    appliesTo: ['video', 'image', 'adjustmentLayer'],
    keyframe: true,
    kind: 'number',
    min: 0,
    max: 100,
    step: 1,
    clamp: 'hard',
    defaultValue: 0,
    ui: { control: 'slider+input' },
  },
];

// Source trim parameters
export const sourceParams: ParamDef[] = [
  {
    id: 'source.trimStart',
    group: 'source',
    label: '源起点',
    appliesTo: ['video', 'audio'],
    keyframe: false,
    kind: 'number',
    min: 0,
    max: 86400,
    step: 0.01,
    unit: 's',
    clamp: 'hard',
    defaultValue: 0,
    ui: { control: 'slider+input', precision: 2 },
  },
  {
    id: 'source.trimEnd',
    group: 'source',
    label: '源终点',
    appliesTo: ['video', 'audio'],
    keyframe: false,
    kind: 'number',
    min: 0,
    max: 86400,
    step: 0.01,
    unit: 's',
    clamp: 'hard',
    defaultValue: 0,
    ui: { control: 'slider+input', precision: 2 },
  },
];

// Speed parameters
export const speedParams: ParamDef[] = [
  {
    id: 'speed.multiplier',
    group: 'speed',
    label: '常规倍数',
    appliesTo: ['video', 'audio'],
    keyframe: false,
    kind: 'number',
    min: 0.1,
    max: 100,
    step: 0.1,
    unit: 'x',
    clamp: 'hard',
    defaultValue: 1.0,
    ui: { control: 'slider+input', precision: 1 },
  },
  {
    id: 'speed.curve',
    group: 'speed',
    label: '曲线变速',
    appliesTo: ['video', 'audio'],
    keyframe: false, // The curve itself acts as keyframes for speed
    kind: 'compound',
    schema: 'curve',
    serialize: 'json',
    defaultValue: {
      points: [
        { t: 0.0, speed: 1.0 },
        { t: 1.0, speed: 1.0 }
      ]
    },
    ui: { control: 'custom' },
  },
  {
    id: 'speed.preservePitch',
    group: 'speed',
    label: '保持音调不变',
    appliesTo: ['video', 'audio'],
    keyframe: false,
    kind: 'boolean',
    defaultValue: true,
    ui: { control: 'switch' },
  },
];

// Audio parameters
export const audioParams: ParamDef[] = [
  {
    id: 'audio.volume',
    group: 'audio',
    label: '音量',
    appliesTo: ['video', 'audio'],
    keyframe: true,
    kind: 'number',
    min: 0,
    max: 200,
    step: 1,
    unit: '%',
    clamp: 'hard',
    defaultValue: 100,
    ui: { control: 'slider+input' },
  },
  {
    id: 'audio.fadeIn',
    group: 'audio',
    label: '淡入',
    appliesTo: ['video', 'audio'],
    keyframe: false,
    kind: 'number',
    min: 0,
    max: 10,
    step: 0.1,
    unit: 's',
    clamp: 'hard',
    defaultValue: 0,
    ui: { control: 'slider+input', precision: 1 },
  },
];

// Text parameters
export const textParams: ParamDef[] = [
  {
    id: 'text.content',
    group: 'text',
    label: '内容',
    appliesTo: ['text'],
    keyframe: false,
    kind: 'compound',
    schema: 'string', // special case
    serialize: 'json',
    defaultValue: { value: '默认文本' }, // wrap in object to satisfy Record<string, any> type
    ui: { control: 'custom' }, // Renders a textarea
  },
  {
    id: 'text.fontFamily',
    group: 'text',
    label: '字体',
    appliesTo: ['text'],
    keyframe: false,
    kind: 'enum',
    defaultValue: 'sans-serif',
    options: [
      { label: '系统默认', value: 'sans-serif' },
      { label: '黑体', value: 'SimHei' },
      { label: '楷体', value: 'KaiTi' },
      { label: '微软雅黑', value: 'Microsoft YaHei' },
      { label: 'Impact', value: 'Impact' },
    ],
    ui: { control: 'select' },
  },
  {
    id: 'text.fontSize',
    group: 'text',
    label: '字号',
    appliesTo: ['text'],
    keyframe: true,
    kind: 'number',
    min: 8,
    max: 400,
    step: 1,
    unit: 'pt',
    clamp: 'hard',
    defaultValue: 100,
    ui: { control: 'slider+input' },
  },
  {
    id: 'text.color',
    group: 'text',
    label: '字体颜色',
    appliesTo: ['text'],
    keyframe: true,
    kind: 'compound',
    schema: 'string',
    serialize: 'json',
    defaultValue: { value: '#ffffff' },
    ui: { control: 'custom' },
  },
  {
    id: 'text.strokeColor',
    group: 'text',
    label: '描边颜色',
    appliesTo: ['text'],
    keyframe: true,
    kind: 'compound',
    schema: 'string',
    serialize: 'json',
    defaultValue: { value: '#000000' },
    ui: { control: 'custom' },
  },
  {
    id: 'text.strokeWidth',
    group: 'text',
    label: '描边宽度',
    appliesTo: ['text'],
    keyframe: true,
    kind: 'number',
    min: 0,
    max: 50,
    step: 1,
    clamp: 'hard',
    defaultValue: 0,
    ui: { control: 'slider+input' },
  },
  {
    id: 'text.shadowColor',
    group: 'text',
    label: '阴影颜色',
    appliesTo: ['text'],
    keyframe: true,
    kind: 'compound',
    schema: 'string',
    serialize: 'json',
    defaultValue: { value: '#000000' },
    ui: { control: 'custom' },
  },
  {
    id: 'text.shadowBlur',
    group: 'text',
    label: '阴影模糊',
    appliesTo: ['text'],
    keyframe: true,
    kind: 'number',
    min: 0,
    max: 100,
    step: 1,
    clamp: 'hard',
    defaultValue: 0,
    ui: { control: 'slider+input' },
  },
  {
    id: 'text.bgColor',
    group: 'text',
    label: '背景框颜色',
    appliesTo: ['text'],
    keyframe: true,
    kind: 'compound',
    schema: 'string',
    serialize: 'json',
    defaultValue: { value: 'transparent' },
    ui: { control: 'custom' },
  },
  {
    id: 'text.animIn',
    group: 'textAnim',
    label: '入场动画',
    appliesTo: ['text'],
    keyframe: false,
    kind: 'enum',
    defaultValue: 'none',
    options: [
      { label: '无', value: 'none' },
      { label: '淡入 (Fade)', value: 'fade' },
      { label: '弹出 (Pop)', value: 'pop' },
      { label: '打字机 (Typewriter)', value: 'typewriter' },
      { label: '上滑 (Slide Up)', value: 'slideUp' },
      { label: '右滑 (Slide Right)', value: 'slideRight' },
      { label: '弹跳 (Bounce)', value: 'bounce' },
      { label: '放大 (Zoom In)', value: 'zoomIn' },
      { label: '抖动 (Shake)', value: 'shake' },
      { label: '故障 (Glitch)', value: 'glitch' },
      { label: '闪烁 (Flicker)', value: 'flicker' },
    ],
    ui: { control: 'select' },
  },
  {
    id: 'text.animInDuration',
    group: 'textAnim',
    label: '入场时长',
    appliesTo: ['text'],
    keyframe: false,
    kind: 'number',
    min: 0,
    max: 10,
    step: 0.1,
    unit: 's',
    clamp: 'hard',
    defaultValue: 0.5,
    ui: { control: 'slider+input', precision: 1 },
  },
  {
    id: 'text.animOut',
    group: 'textAnim',
    label: '出场动画',
    appliesTo: ['text'],
    keyframe: false,
    kind: 'enum',
    defaultValue: 'none',
    options: [
      { label: '无', value: 'none' },
      { label: '淡出 (Fade)', value: 'fade' },
      { label: '缩小 (Pop Out)', value: 'popOut' },
      { label: '下滑 (Slide Down)', value: 'slideDown' },
      { label: '左滑 (Slide Left)', value: 'slideLeft' },
      { label: '弹跳消失 (Bounce Out)', value: 'bounceOut' },
      { label: '缩放消失 (Zoom Out)', value: 'zoomOut' },
      { label: '故障消失 (Glitch Out)', value: 'glitchOut' },
    ],
    ui: { control: 'select' },
  },
  {
    id: 'text.charStagger',
    group: 'textAnim',
    label: '逐字间隔',
    appliesTo: ['text'],
    keyframe: false,
    kind: 'number',
    min: 0,
    max: 0.5,
    step: 0.01,
    unit: 's',
    clamp: 'hard',
    defaultValue: 0.05,
    ui: { control: 'slider+input', precision: 2 },
  },
  {
    id: 'text.animOutDuration',
    group: 'textAnim',
    label: '出场时长',
    appliesTo: ['text'],
    keyframe: false,
    kind: 'number',
    min: 0,
    max: 10,
    step: 0.1,
    unit: 's',
    clamp: 'hard',
    defaultValue: 0.5,
    ui: { control: 'slider+input', precision: 1 },
  },
];

// Compound parameter examples (curves, hsl)
export const advancedCompoundParams: ParamDef[] = [
  {
    id: 'color.hsl',
    group: 'hsl',
    label: 'HSL (8色)',
    appliesTo: ['video', 'image', 'adjustmentLayer'],
    keyframe: true, // Keyframes the entire HSL structure
    kind: 'compound',
    schema: 'hsl',
    serialize: 'json',
    interpolation: 'hold', // As agreed in spec
    defaultValue: {
      red: { h: 0, s: 0, l: 0 },
      orange: { h: 0, s: 0, l: 0 },
      yellow: { h: 0, s: 0, l: 0 },
      green: { h: 0, s: 0, l: 0 },
      cyan: { h: 0, s: 0, l: 0 },
      blue: { h: 0, s: 0, l: 0 },
      purple: { h: 0, s: 0, l: 0 },
      magenta: { h: 0, s: 0, l: 0 },
    },
    ui: { control: 'custom' },
  },
  {
    id: 'color.curves',
    group: 'curves',
    label: 'RGB 曲线',
    appliesTo: ['video', 'image', 'adjustmentLayer'],
    keyframe: true,
    kind: 'compound',
    schema: 'curve',
    serialize: 'json',
    interpolation: 'hold',
    defaultValue: {
      rgb: [[0, 0], [255, 255]],
      r: [[0, 0], [255, 255]],
      g: [[0, 0], [255, 255]],
      b: [[0, 0], [255, 255]],
    },
    ui: { control: 'custom' },
  },
];

// Transition parameters
export const transitionParams: ParamDef[] = [
  {
    id: 'transition.type',
    group: 'transform',
    label: '转场类型',
    appliesTo: ['transition'],
    keyframe: false,
    kind: 'enum',
    defaultValue: 'dissolve',
    options: [
      { label: '交叉溶解 (Dissolve)', value: 'dissolve' },
      { label: '推移 (Push)', value: 'push' },
      { label: '擦除 (Wipe)', value: 'wipe' },
    ],
    ui: { control: 'select' },
  },
  {
    id: 'transition.progress',
    group: 'transform',
    label: '进度 (内部使用)',
    appliesTo: ['transition'],
    keyframe: false,
    kind: 'number',
    min: 0,
    max: 100,
    step: 1,
    clamp: 'hard',
    defaultValue: 0,
    ui: { control: 'slider+input' },
  }
];

// Effects parameters
export const effectParams: ParamDef[] = [
  {
    id: 'effect.blur',
    group: 'effects',
    label: '高斯模糊',
    appliesTo: ['video', 'image', 'adjustmentLayer'],
    keyframe: true,
    kind: 'number',
    min: 0,
    max: 100,
    step: 1,
    clamp: 'hard',
    defaultValue: 0,
    ui: { control: 'slider+input' },
  },
  {
    id: 'effect.grayscale',
    group: 'effects',
    label: '黑白(去色)',
    appliesTo: ['video', 'image', 'adjustmentLayer'],
    keyframe: true,
    kind: 'number',
    min: 0,
    max: 100,
    step: 1,
    clamp: 'hard',
    defaultValue: 0,
    ui: { control: 'slider+input' },
  },
  {
    id: 'effect.glitch',
    group: 'effects',
    label: '故障干扰',
    appliesTo: ['video', 'image', 'adjustmentLayer'],
    keyframe: true,
    kind: 'number',
    min: 0,
    max: 100,
    step: 1,
    clamp: 'hard',
    defaultValue: 0,
    ui: { control: 'slider+input' },
  },
];

// Shape parameters
export const shapeParams: ParamDef[] = [
  {
    id: 'shape.type',
    group: 'transform',
    label: '形状类型',
    appliesTo: ['shape'],
    keyframe: false,
    kind: 'enum',
    defaultValue: 'rectangle',
    options: [
      { label: '矩形 (Rectangle)', value: 'rectangle' },
      { label: '圆形 (Circle)', value: 'circle' },
      { label: '椭圆 (Ellipse)', value: 'ellipse' },
      { label: '三角形 (Triangle)', value: 'triangle' },
    ],
    ui: { control: 'select' },
  },
  {
    id: 'shape.fillColor',
    group: 'transform',
    label: '填充颜色',
    appliesTo: ['shape'],
    keyframe: true,
    kind: 'compound',
    schema: 'string',
    serialize: 'json',
    defaultValue: { value: '#ffffff' },
    ui: { control: 'custom' },
  },
  {
    id: 'shape.strokeColor',
    group: 'transform',
    label: '边框颜色',
    appliesTo: ['shape'],
    keyframe: true,
    kind: 'compound',
    schema: 'string',
    serialize: 'json',
    defaultValue: { value: 'transparent' },
    ui: { control: 'custom' },
  },
  {
    id: 'shape.strokeWidth',
    group: 'transform',
    label: '边框宽度',
    appliesTo: ['shape'],
    keyframe: true,
    kind: 'number',
    min: 0,
    max: 100,
    step: 1,
    unit: 'px',
    clamp: 'hard',
    defaultValue: 0,
    ui: { control: 'slider+input' },
  },
  {
    id: 'shape.cornerRadius',
    group: 'transform',
    label: '圆角',
    appliesTo: ['shape'],
    keyframe: true,
    kind: 'number',
    min: 0,
    max: 500,
    step: 1,
    unit: 'px',
    clamp: 'hard',
    defaultValue: 0,
    ui: { control: 'slider+input' },
  },
];

// Mask parameters
export const maskParams: ParamDef[] = [
  {
    id: 'mask.type',
    group: 'mask',
    label: '蒙版类型',
    appliesTo: ['video', 'image', 'adjustmentLayer'],
    keyframe: false,
    kind: 'enum',
    defaultValue: 'none',
    options: [
      { label: '无 (None)', value: 'none' },
      { label: '矩形 (Rectangle)', value: 'rectangle' },
      { label: '圆形 (Circle)', value: 'circle' },
    ],
    ui: { control: 'select' },
  },
  {
    id: 'mask.position.x',
    group: 'mask',
    label: '中心 X',
    appliesTo: ['video', 'image', 'adjustmentLayer'],
    keyframe: true,
    kind: 'number',
    min: -100,
    max: 200,
    step: 0.1,
    unit: '%',
    clamp: 'soft',
    defaultValue: 50,
    ui: { control: 'slider+input', precision: 1 },
  },
  {
    id: 'mask.position.y',
    group: 'mask',
    label: '中心 Y',
    appliesTo: ['video', 'image', 'adjustmentLayer'],
    keyframe: true,
    kind: 'number',
    min: -100,
    max: 200,
    step: 0.1,
    unit: '%',
    clamp: 'soft',
    defaultValue: 50,
    ui: { control: 'slider+input', precision: 1 },
  },
  {
    id: 'mask.size.width',
    group: 'mask',
    label: '宽度 / 长轴',
    appliesTo: ['video', 'image', 'adjustmentLayer'],
    keyframe: true,
    kind: 'number',
    min: 0,
    max: 200,
    step: 0.1,
    unit: '%',
    clamp: 'soft',
    defaultValue: 50,
    ui: { control: 'slider+input', precision: 1 },
  },
  {
    id: 'mask.size.height',
    group: 'mask',
    label: '高度 / 短轴',
    appliesTo: ['video', 'image', 'adjustmentLayer'],
    keyframe: true,
    kind: 'number',
    min: 0,
    max: 200,
    step: 0.1,
    unit: '%',
    clamp: 'soft',
    defaultValue: 50,
    ui: { control: 'slider+input', precision: 1 },
  },
  {
    id: 'mask.feather',
    group: 'mask',
    label: '羽化 (Feather)',
    appliesTo: ['video', 'image', 'adjustmentLayer'],
    keyframe: true,
    kind: 'number',
    min: 0,
    max: 100,
    step: 0.1,
    unit: '%',
    clamp: 'hard',
    defaultValue: 0,
    ui: { control: 'slider+input', precision: 1 },
  },
  {
    id: 'mask.invert',
    group: 'mask',
    label: '反转 (Invert)',
    appliesTo: ['video', 'image', 'adjustmentLayer'],
    keyframe: false,
    kind: 'boolean',
    defaultValue: false,
    ui: { control: 'switch' },
  },
];

// Assemble the single source of truth
export const ALL_PARAMS: ParamDef[] = [
  ...transformParams,
  ...colorBasicParams,
  ...lutParams,
  ...effectParams,
  ...sourceParams,
  ...speedParams,
  ...audioParams,
  ...textParams,
  ...advancedCompoundParams,
  ...transitionParams,
  ...maskParams,
  ...shapeParams,
];
